default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-twitter_development

test:
  <<: *default
  database: rails-twitter_test



production:
  <<: *default
  database: rails-twitter_production
  username: rails-twitter
  password: <%= ENV['RAILS-TWITTER_DATABASE_PASSWORD'] %>
